// Mock 데이터베이스 역할을 할 제품 데이터
// 주의: SPA 등록 페이지에서 추가/수정한 항목은 localStorage('customProductsOverlay')에 저장되어
// 여기 기본 목록에 병합되어 표시됩니다. (페이지 새로고침/오프라인에서도 유지)
import {
  dogFood,
  catToy,
  petCarrier,
  birdFood,
  dogBall,
  catBowl,
  dogHarness,
  petShampoo,
  birdRopeType,
  birdToy,
  foodBirdOwlSee,
  foodBirdScream,
  foodCatFifty,
  foodCatFishTaste,
  foodCatGoddu,
  foodDogAddyLovesIt,
  foodDogAndCatDried,
  foodDogCatMoistured,
  foodDogGum1,
  foodDogMeat,
  lizardFeedPlate,
  lizardPackage,
  lizardTeralium,
  petContainerSpray,
  petDigitalMeasurer,
  petFloorPad,
  petFoodAutoFeeder,
  petHeatLamp,
  petPinsetFeed,
  petShelter,
  petWaterContainerTypeFeeder,
  productCatBellNecklace,
  productCatBowl,
  productCatHygienePad,
  productDogBowl,
  productDogHygienePad,
  productDogWaterBowl,
  productHygienePlasticBag,
  productHygieneToilet,
  productPetBed,
  productPetCage,
  productPetComb,
  productPetCousion,
  productPetCutter,
  productPetEarCleaner,
  productPetHouse,
  productPetNecklace,
  toyCatSmartLaser,
  toyDogBone,
  toyDogRope,
  walkDogLEDLeash,
  walkDogNeckLeash,
  walkDogShoes,
  walkPetBag,
  walkWaterContainer
} from './images.js';

export const mockProductsDatabase = [
  // 기존 8개 제품
  {
    no: 1,
    name: '강아지 사료',
    price: 25000,
    originalPrice: 30000,
    category: '사료',
    imageUrl: dogFood,
    description: '영양 만점 강아지 사료로 반려견의 건강한 성장을 도와줍니다. 신선한 육류와 곡물로 만들어진 프리미엄 사료로, 강아지의 나이와 체중에 맞게 급여하시면 됩니다.',
    stock: 50,
    status: '판매중',
    rating: 4.5,
    reviewCount: '120개 리뷰',
    isNew: true,
    discount: '20% 할인',
    views: 150,
    likes: 25,
    favorites: 30
  },
  {
    no: 2,
    name: '고양이 장난감 막대',
    price: 12000,
    originalPrice: 15000,
    category: '장난감',
    imageUrl: catToy,
    description: '고양이가 좋아하는 재미있는 장난감 막대입니다. 깃털과 방울이 달려있어 고양이의 사냥 본능을 자극하고 스트레스를 해소해줍니다.',
    stock: 30,
    status: '판매중',
    rating: 4.2,
    reviewCount: '89개 리뷰',
    isNew: true,
    discount: '20% 할인',
    views: 120,
    likes: 15,
    favorites: 18
  },
  {
    no: 3,
    name: '펫 캐리어',
    price: 35000,
    originalPrice: 45000,
    category: '용품',
    imageUrl: petCarrier,
    description: '반려동물을 안전하게 이동시킬 수 있는 캐리어입니다. 통풍이 잘 되고 견고한 구조로 되어있어 장거리 이동에도 안전합니다.',
    stock: 25,
    status: '판매중',
    rating: 4.7,
    reviewCount: '156개 리뷰',
    isNew: false,
    discount: '22% 할인',
    views: 200,
    likes: 35,
    favorites: 45
  },
  {
    no: 4,
    name: '새 모이',
    price: 8000,
    originalPrice: 10000,
    category: '사료',
    imageUrl: birdFood,
    description: '새들이 좋아하는 영양 모이입니다. 다양한 곡물과 씨앗이 포함되어 새의 건강한 성장을 돕습니다.',
    stock: 40,
    status: '판매중',
    rating: 4.3,
    reviewCount: '95개 리뷰',
    isNew: true,
    discount: '20% 할인',
    views: 80,
    likes: 12,
    favorites: 15
  },
  {
    no: 5,
    name: '강아지 공',
    price: 15000,
    originalPrice: 18000,
    category: '장난감',
    imageUrl: dogBall,
    description: '강아지가 좋아하는 탄력 있는 공입니다. 안전한 재질로 만들어져 실내외에서 안전하게 놀 수 있습니다.',
    stock: 35,
    status: '판매중',
    rating: 4.6,
    reviewCount: '142개 리뷰',
    isNew: false,
    discount: '17% 할인',
    views: 180,
    likes: 28,
    favorites: 32
  },
  {
    no: 6,
    name: '고양이 물그릇',
    price: 22000,
    originalPrice: 28000,
    category: '용품',
    imageUrl: catBowl,
    description: '고양이 전용 물그릇입니다. 위생적이고 미끄럼 방지 바닥으로 안정적입니다.',
    stock: 20,
    status: '판매중',
    rating: 4.4,
    reviewCount: '76개 리뷰',
    isNew: true,
    discount: '21% 할인',
    views: 95,
    likes: 18,
    favorites: 22
  },
  {
    no: 7,
    name: '강아지 하네스',
    price: 18000,
    originalPrice: 22000,
    category: '산책',
    imageUrl: dogHarness,
    description: '편안한 강아지 하네스입니다. 부드러운 재질로 강아지가 편안하게 산책할 수 있습니다.',
    stock: 28,
    status: '판매중',
    rating: 4.5,
    reviewCount: '134개 리뷰',
    isNew: true,
    discount: '18% 할인',
    views: 165,
    likes: 24,
    favorites: 28
  },
  {
    no: 8,
    name: '펫 샴푸',
    price: 16000,
    originalPrice: 20000,
    category: '용품',
    imageUrl: petShampoo,
    description: '반려동물 전용 샴푸입니다. 민감한 피부에도 자극이 적고 부드럽게 세정합니다.',
    stock: 32,
    status: '판매중',
    rating: 4.1,
    reviewCount: '87개 리뷰',
    isNew: false,
    discount: '20% 할인',
    views: 110,
    likes: 16,
    favorites: 19
  },
  
  // 추가 44개 제품
  {
    no: 9,
    name: '새 로프 장난감',
    price: 9000,
    originalPrice: 12000,
    category: '장난감',
    imageUrl: birdRopeType,
    description: '새들이 좋아하는 로프 타입 장난감입니다. 자연 섬유로 만들어져 안전하고 재미있게 놀 수 있습니다.',
    stock: 45,
    status: '판매중',
    rating: 4.2,
    reviewCount: '67개 리뷰',
    isNew: true,
    discount: '25% 할인',
    views: 85,
    likes: 14,
    favorites: 17
  },
  {
    no: 10,
    name: '새 놀이 장난감',
    price: 11000,
    originalPrice: 14000,
    category: '장난감',
    imageUrl: birdToy,
    description: '새의 지능 발달에 도움이 되는 놀이 장난감입니다. 다양한 색상과 소재로 구성되어 있습니다.',
    stock: 38,
    status: '판매중',
    rating: 4.4,
    reviewCount: '92개 리뷰',
    isNew: false,
    discount: '21% 할인',
    views: 102,
    likes: 19,
    favorites: 24
  },
  {
    no: 11,
    name: '부엉이 새 사료',
    price: 13000,
    originalPrice: 16000,
    category: '사료',
    imageUrl: foodBirdOwlSee,
    description: '부엉이와 맹금류를 위한 특별한 사료입니다. 고단백 영양소가 풍부합니다.',
    stock: 22,
    status: '판매중',
    rating: 4.6,
    reviewCount: '45개 리뷰',
    isNew: true,
    discount: '19% 할인',
    views: 68,
    likes: 11,
    favorites: 13
  },
  {
    no: 12,
    name: '새 전용 프리미엄 사료',
    price: 15000,
    originalPrice: 19000,
    category: '사료',
    imageUrl: foodBirdScream,
    description: '새들의 건강한 성장을 위한 프리미엄 사료입니다. 비타민과 미네랄이 균형있게 포함되어 있습니다.',
    stock: 33,
    status: '판매중',
    rating: 4.3,
    reviewCount: '78개 리뷰',
    isNew: false,
    discount: '21% 할인',
    views: 115,
    likes: 16,
    favorites: 20
  },
  {
    no: 13,
    name: '고양이 건식 사료 50',
    price: 32000,
    originalPrice: 40000,
    category: '사료',
    imageUrl: foodCatFifty,
    description: '성묘를 위한 건식 사료입니다. 50일 분량으로 경제적이고 영양가가 풍부합니다.',
    stock: 18,
    status: '판매중',
    rating: 4.7,
    reviewCount: '134개 리뷰',
    isNew: true,
    discount: '20% 할인',
    views: 201,
    likes: 35,
    favorites: 42
  },
  {
    no: 14,
    name: '고양이 생선맛 사료',
    price: 28000,
    originalPrice: 35000,
    category: '사료',
    imageUrl: foodCatFishTaste,
    description: '고양이가 좋아하는 생선맛 사료입니다. 오메가3가 풍부하고 소화가 잘 됩니다.',
    stock: 26,
    status: '판매중',
    rating: 4.5,
    reviewCount: '167개 리뷰',
    isNew: false,
    discount: '20% 할인',
    views: 189,
    likes: 31,
    favorites: 38
  },
  {
    no: 15,
    name: '고양이 프리미엄 사료',
    price: 35000,
    originalPrice: 42000,
    category: '사료',
    imageUrl: foodCatGoddu,
    description: '고급 재료로 만든 고양이 프리미엄 사료입니다. 털 윤기와 소화 건강을 동시에 케어합니다.',
    stock: 15,
    status: '판매중',
    rating: 4.8,
    reviewCount: '203개 리뷰',
    isNew: true,
    discount: '17% 할인',
    views: 245,
    likes: 48,
    favorites: 56
  },
  {
    no: 16,
    name: '강아지 사랑 사료',
    price: 29000,
    originalPrice: 36000,
    category: '사료',
    imageUrl: foodDogAddyLovesIt,
    description: '강아지가 사랑하는 맛있는 사료입니다. 자연 재료로만 만들어져 건강하고 맛있습니다.',
    stock: 42,
    status: '판매중',
    rating: 4.6,
    reviewCount: '178개 리뷰',
    isNew: false,
    discount: '19% 할인',
    views: 156,
    likes: 27,
    favorites: 33
  },
  {
    no: 17,
    name: '강아지 고양이 건식 사료',
    price: 26000,
    originalPrice: 32000,
    category: '사료',
    imageUrl: foodDogAndCatDried,
    description: '강아지와 고양이 모두 먹을 수 있는 건식 사료입니다. 다양한 영양소가 균형있게 포함되어 있습니다.',
    stock: 37,
    status: '판매중',
    rating: 4.4,
    reviewCount: '145개 리뷰',
    isNew: true,
    discount: '19% 할인',
    views: 132,
    likes: 23,
    favorites: 29
  },
  {
    no: 18,
    name: '강아지 고양이 습식 사료',
    price: 24000,
    originalPrice: 30000,
    category: '사료',
    imageUrl: foodDogCatMoistured,
    description: '수분이 풍부한 습식 사료입니다. 강아지와 고양이 모두에게 좋은 영양 공급원입니다.',
    stock: 29,
    status: '판매중',
    rating: 4.3,
    reviewCount: '98개 리뷰',
    isNew: false,
    discount: '20% 할인',
    views: 108,
    likes: 19,
    favorites: 25
  },
  {
    no: 19,
    name: '강아지 껌 사료',
    price: 18000,
    originalPrice: 23000,
    category: '사료',
    imageUrl: foodDogGum1,
    description: '강아지의 치아 건강에 도움이 되는 껌 타입 사료입니다. 씹는 재미와 영양을 동시에 제공합니다.',
    stock: 55,
    status: '판매중',
    rating: 4.2,
    reviewCount: '87개 리뷰',
    isNew: true,
    discount: '22% 할인',
    views: 93,
    likes: 16,
    favorites: 21
  },
  {
    no: 20,
    name: '강아지 육류 사료',
    price: 38000,
    originalPrice: 45000,
    category: '사료',
    imageUrl: foodDogMeat,
    description: '신선한 육류를 주원료로 한 강아지 사료입니다. 고단백 저지방으로 건강한 성장을 돕습니다.',
    stock: 21,
    status: '판매중',
    rating: 4.9,
    reviewCount: '256개 리뷰',
    isNew: true,
    discount: '16% 할인',
    views: 298,
    likes: 52,
    favorites: 67
  },
  {
    no: 21,
    name: '도마뱀 사료 접시',
    price: 12000,
    originalPrice: 15000,
    category: '용품',
    imageUrl: lizardFeedPlate,
    description: '도마뱀과 파충류를 위한 전용 사료 접시입니다. 청결하고 사용하기 편리합니다.',
    stock: 34,
    status: '판매중',
    rating: 4.1,
    reviewCount: '43개 리뷰',
    isNew: false,
    discount: '20% 할인',
    views: 67,
    likes: 9,
    favorites: 12
  },
  {
    no: 22,
    name: '도마뱀 케어 패키지',
    price: 45000,
    originalPrice: 55000,
    category: '용품',
    imageUrl: lizardPackage,
    description: '도마뱀 사육에 필요한 모든 용품이 들어있는 패키지입니다. 초보자도 쉽게 시작할 수 있습니다.',
    stock: 12,
    status: '판매중',
    rating: 4.6,
    reviewCount: '78개 리뷰',
    isNew: true,
    discount: '18% 할인',
    views: 145,
    likes: 28,
    favorites: 35
  },
  {
    no: 23,
    name: '도마뱀 테라리움',
    price: 89000,
    originalPrice: 110000,
    category: '용품',
    imageUrl: lizardTeralium,
    description: '도마뱀을 위한 전문적인 테라리움입니다. 온도와 습도 조절이 가능하여 최적의 환경을 제공합니다.',
    stock: 8,
    status: '판매중',
    rating: 4.8,
    reviewCount: '124개 리뷰',
    isNew: true,
    discount: '19% 할인',
    views: 234,
    likes: 45,
    favorites: 58
  },
  {
    no: 24,
    name: '펫 스프레이 용기',
    price: 8000,
    originalPrice: 10000,
    category: '용품',
    imageUrl: petContainerSpray,
    description: '반려동물 케어용 스프레이 용기입니다. 미스트 타입으로 균일하게 분사됩니다.',
    stock: 48,
    status: '판매중',
    rating: 4.0,
    reviewCount: '56개 리뷰',
    isNew: false,
    discount: '20% 할인',
    views: 72,
    likes: 12,
    favorites: 15
  },
  {
    no: 25,
    name: '펫 디지털 계량기',
    price: 25000,
    originalPrice: 32000,
    category: '용품',
    imageUrl: petDigitalMeasurer,
    description: '정확한 사료 계량을 위한 디지털 계량기입니다. 반려동물의 적정 사료량 관리에 도움됩니다.',
    stock: 19,
    status: '판매중',
    rating: 4.5,
    reviewCount: '89개 리뷰',
    isNew: true,
    discount: '22% 할인',
    views: 126,
    likes: 23,
    favorites: 28
  },
  {
    no: 26,
    name: '펫 바닥 매트',
    price: 15000,
    originalPrice: 20000,
    category: '용품',
    imageUrl: petFloorPad,
    description: '반려동물을 위한 바닥 보호 매트입니다. 미끄럼 방지와 충격 완화 기능이 있습니다.',
    stock: 41,
    status: '판매중',
    rating: 4.3,
    reviewCount: '112개 리뷰',
    isNew: false,
    discount: '25% 할인',
    views: 98,
    likes: 18,
    favorites: 22
  },
  {
    no: 27,
    name: '자동 급식기',
    price: 78000,
    originalPrice: 95000,
    category: '용품',
    imageUrl: petFoodAutoFeeder,
    description: '스마트 자동 급식기입니다. 정해진 시간에 자동으로 사료를 공급하여 규칙적인 식사를 도와줍니다.',
    stock: 14,
    status: '판매중',
    rating: 4.7,
    reviewCount: '167개 리뷰',
    isNew: true,
    discount: '18% 할인',
    views: 289,
    likes: 54,
    favorites: 67
  },
  {
    no: 28,
    name: '펫 보온등',
    price: 35000,
    originalPrice: 42000,
    category: '용품',
    imageUrl: petHeatLamp,
    description: '파충류와 소동물을 위한 보온등입니다. 적절한 온도 유지로 건강한 환경을 제공합니다.',
    stock: 23,
    status: '판매중',
    rating: 4.4,
    reviewCount: '93개 리뷰',
    isNew: false,
    discount: '17% 할인',
    views: 145,
    likes: 26,
    favorites: 32
  },
  {
    no: 29,
    name: '펫 핀셋 급식기',
    price: 6000,
    originalPrice: 8000,
    category: '용품',
    imageUrl: petPinsetFeed,
    description: '소형 펫을 위한 핀셋 타입 급식기입니다. 정확하고 위생적인 급식이 가능합니다.',
    stock: 52,
    status: '판매중',
    rating: 4.2,
    reviewCount: '67개 리뷰',
    isNew: true,
    discount: '25% 할인',
    views: 78,
    likes: 13,
    favorites: 16
  },
  {
    no: 30,
    name: '펫 쉘터',
    price: 42000,
    originalPrice: 52000,
    category: '용품',
    imageUrl: petShelter,
    description: '반려동물을 위한 아늑한 쉘터입니다. 안전하고 편안한 휴식 공간을 제공합니다.',
    stock: 17,
    status: '판매중',
    rating: 4.6,
    reviewCount: '134개 리뷰',
    isNew: true,
    discount: '19% 할인',
    views: 187,
    likes: 34,
    favorites: 41
  },
  {
    no: 31,
    name: '자동 급수기',
    price: 32000,
    originalPrice: 38000,
    category: '용품',
    imageUrl: petWaterContainerTypeFeeder,
    description: '물이 자동으로 보충되는 급수기입니다. 항상 신선한 물을 공급하여 반려동물의 건강을 지킵니다.',
    stock: 28,
    status: '판매중',
    rating: 4.5,
    reviewCount: '156개 리뷰',
    isNew: false,
    discount: '16% 할인',
    views: 203,
    likes: 37,
    favorites: 44
  },
  {
    no: 32,
    name: '고양이 방울 목걸이',
    price: 9000,
    originalPrice: 12000,
    category: '액세서리',
    imageUrl: productCatBellNecklace,
    description: '고양이를 위한 귀여운 방울 목걸이입니다. 안전한 재질로 만들어져 목에 부담을 주지 않습니다.',
    stock: 46,
    status: '판매중',
    rating: 4.1,
    reviewCount: '82개 리뷰',
    isNew: true,
    discount: '25% 할인',
    views: 95,
    likes: 17,
    favorites: 21
  },
  {
    no: 33,
    name: '고양이 사료그릇',
    price: 18000,
    originalPrice: 23000,
    category: '용품',
    imageUrl: productCatBowl,
    description: '고양이 전용 사료그릇입니다. 적절한 높이와 크기로 편안한 식사를 도와줍니다.',
    stock: 35,
    status: '판매중',
    rating: 4.4,
    reviewCount: '127개 리뷰',
    isNew: false,
    discount: '22% 할인',
    views: 142,
    likes: 25,
    favorites: 31
  },
  {
    no: 34,
    name: '고양이 위생패드',
    price: 16000,
    originalPrice: 20000,
    category: '위생용품',
    imageUrl: productCatHygienePad,
    description: '고양이 화장실용 위생패드입니다. 흡수력이 뛰어나고 냄새 제거 기능이 있습니다.',
    stock: 39,
    status: '판매중',
    rating: 4.3,
    reviewCount: '98개 리뷰',
    isNew: true,
    discount: '20% 할인',
    views: 118,
    likes: 21,
    favorites: 26
  },
  {
    no: 35,
    name: '강아지 사료그릇',
    price: 20000,
    originalPrice: 25000,
    category: '용품',
    imageUrl: productDogBowl,
    description: '강아지를 위한 스테인리스 사료그릇입니다. 위생적이고 내구성이 뛰어납니다.',
    stock: 31,
    status: '판매중',
    rating: 4.6,
    reviewCount: '145개 리뷰',
    isNew: false,
    discount: '20% 할인',
    views: 167,
    likes: 29,
    favorites: 36
  },
  {
    no: 36,
    name: '강아지 위생패드',
    price: 22000,
    originalPrice: 28000,
    category: '위생용품',
    imageUrl: productDogHygienePad,
    description: '강아지용 대형 위생패드입니다. 넓은 면적으로 흡수력이 우수하고 바닥 보호 효과가 있습니다.',
    stock: 44,
    status: '판매중',
    rating: 4.5,
    reviewCount: '189개 리뷰',
    isNew: true,
    discount: '21% 할인',
    views: 201,
    likes: 36,
    favorites: 43
  },
  {
    no: 37,
    name: '강아지 급수그릇',
    price: 17000,
    originalPrice: 22000,
    category: '용품',
    imageUrl: productDogWaterBowl,
    description: '강아지 전용 급수그릇입니다. 미끄럼 방지 바닥과 적절한 깊이로 설계되었습니다.',
    stock: 38,
    status: '판매중',
    rating: 4.2,
    reviewCount: '93개 리뷰',
    isNew: false,
    discount: '23% 할인',
    views: 108,
    likes: 19,
    favorites: 24
  },
  {
    no: 38,
    name: '위생봉투',
    price: 5000,
    originalPrice: 7000,
    category: '위생용품',
    imageUrl: productHygienePlasticBag,
    description: '반려동물 배변 처리용 위생봉투입니다. 생분해성 소재로 환경 친화적입니다.',
    stock: 89,
    status: '판매중',
    rating: 4.0,
    reviewCount: '234개 리뷰',
    isNew: true,
    discount: '29% 할인',
    views: 167,
    likes: 28,
    favorites: 34
  },
  {
    no: 39,
    name: '펫 화장실',
    price: 35000,
    originalPrice: 45000,
    category: '위생용품',
    imageUrl: productHygieneToilet,
    description: '실내용 펫 화장실입니다. 냄새 차단과 청소가 쉬운 구조로 설계되었습니다.',
    stock: 16,
    status: '판매중',
    rating: 4.7,
    reviewCount: '156개 리뷰',
    isNew: true,
    discount: '22% 할인',
    views: 234,
    likes: 42,
    favorites: 51
  },
  {
    no: 40,
    name: '펫 침대',
    price: 28000,
    originalPrice: 35000,
    category: '용품',
    imageUrl: productPetBed,
    description: '반려동물을 위한 편안한 침대입니다. 부드러운 소재와 적절한 쿠션감으로 숙면을 도와줍니다.',
    stock: 25,
    status: '판매중',
    rating: 4.8,
    reviewCount: '178개 리뷰',
    isNew: false,
    discount: '20% 할인',
    views: 267,
    likes: 48,
    favorites: 58
  },
  {
    no: 41,
    name: '펫 케이지',
    price: 65000,
    originalPrice: 80000,
    category: '용품',
    imageUrl: productPetCage,
    description: '안전하고 튼튼한 펫 케이지입니다. 접이식 구조로 보관과 이동이 편리합니다.',
    stock: 11,
    status: '판매중',
    rating: 4.6,
    reviewCount: '134개 리뷰',
    isNew: true,
    discount: '19% 할인',
    views: 189,
    likes: 34,
    favorites: 41
  },
  {
    no: 42,
    name: '펫 빗',
    price: 12000,
    originalPrice: 15000,
    category: '미용용품',
    imageUrl: productPetComb,
    description: '반려동물 전용 빗입니다. 부드러운 핀으로 털 엉킴을 방지하고 마사지 효과도 있습니다.',
    stock: 47,
    status: '판매중',
    rating: 4.3,
    reviewCount: '87개 리뷰',
    isNew: false,
    discount: '20% 할인',
    views: 98,
    likes: 17,
    favorites: 21
  },
  {
    no: 43,
    name: '펫 쿠션',
    price: 24000,
    originalPrice: 30000,
    category: '용품',
    imageUrl: productPetCousion,
    description: '반려동물을 위한 편안한 쿠션입니다. 방수 커버로 세탁이 쉽고 위생적입니다.',
    stock: 33,
    status: '판매중',
    rating: 4.4,
    reviewCount: '112개 리뷰',
    isNew: true,
    discount: '20% 할인',
    views: 145,
    likes: 26,
    favorites: 32
  },
  {
    no: 44,
    name: '펫 발톱깎이',
    price: 8000,
    originalPrice: 11000,
    category: '미용용품',
    imageUrl: productPetCutter,
    description: '안전한 펫 발톱깎이입니다. 날카로운 날과 안전장치로 정확하고 안전한 발톱 관리가 가능합니다.',
    stock: 56,
    status: '판매중',
    rating: 4.1,
    reviewCount: '76개 리뷰',
    isNew: false,
    discount: '27% 할인',
    views: 89,
    likes: 15,
    favorites: 19
  },
  {
    no: 45,
    name: '펫 귀 청소제',
    price: 15000,
    originalPrice: 19000,
    category: '미용용품',
    imageUrl: productPetEarCleaner,
    description: '반려동물 귀 전용 청소제입니다. 순한 성분으로 안전하게 귀 건강을 관리할 수 있습니다.',
    stock: 41,
    status: '판매중',
    rating: 4.5,
    reviewCount: '123개 리뷰',
    isNew: true,
    discount: '21% 할인',
    views: 134,
    likes: 24,
    favorites: 29
  },
  {
    no: 46,
    name: '펫 하우스',
    price: 45000,
    originalPrice: 58000,
    category: '용품',
    imageUrl: productPetHouse,
    description: '반려동물을 위한 아늑한 하우스입니다. 실내외 모두 사용 가능하며 조립이 간단합니다.',
    stock: 19,
    status: '판매중',
    rating: 4.7,
    reviewCount: '145개 리뷰',
    isNew: true,
    discount: '22% 할인',
    views: 201,
    likes: 38,
    favorites: 46
  },
  {
    no: 47,
    name: '펫 목걸이',
    price: 13000,
    originalPrice: 17000,
    category: '액세서리',
    imageUrl: productPetNecklace,
    description: '반려동물용 패션 목걸이입니다. 다양한 디자인으로 개성을 표현할 수 있습니다.',
    stock: 37,
    status: '판매중',
    rating: 4.2,
    reviewCount: '89개 리뷰',
    isNew: false,
    discount: '24% 할인',
    views: 106,
    likes: 19,
    favorites: 23
  },
  {
    no: 48,
    name: '고양이 스마트 레이저 장난감',
    price: 35000,
    originalPrice: 45000,
    category: '장난감',
    imageUrl: toyCatSmartLaser,
    description: '자동으로 움직이는 스마트 레이저 장난감입니다. 고양이의 운동량 증가와 스트레스 해소에 도움됩니다.',
    stock: 22,
    status: '판매중',
    rating: 4.6,
    reviewCount: '167개 리뷰',
    isNew: true,
    discount: '22% 할인',
    views: 245,
    likes: 44,
    favorites: 53
  },
  {
    no: 49,
    name: '강아지 뼈다귀 장난감',
    price: 10000,
    originalPrice: 13000,
    category: '장난감',
    imageUrl: toyDogBone,
    description: '강아지가 좋아하는 뼈다귀 모양 장난감입니다. 안전한 소재로 만들어져 오래 씹어도 안전합니다.',
    stock: 48,
    status: '판매중',
    rating: 4.3,
    reviewCount: '124개 리뷰',
    isNew: false,
    discount: '23% 할인',
    views: 134,
    likes: 23,
    favorites: 28
  },
  {
    no: 50,
    name: '강아지 로프 장난감',
    price: 7000,
    originalPrice: 9000,
    category: '장난감',
    imageUrl: toyDogRope,
    description: '천연 소재로 만든 강아지 로프 장난감입니다. 치아 건강에 도움이 되고 놀이와 훈련에 활용할 수 있습니다.',
    stock: 62,
    status: '판매중',
    rating: 4.1,
    reviewCount: '98개 리뷰',
    isNew: true,
    discount: '22% 할인',
    views: 87,
    likes: 16,
    favorites: 20
  },
  {
    no: 51,
    name: 'LED 강아지 목줄',
    price: 25000,
    originalPrice: 32000,
    category: '산책',
    imageUrl: walkDogLEDLeash,
    description: '야간 산책을 위한 LED 강아지 목줄입니다. 충전식 배터리와 다양한 점멸 모드로 안전한 야간 산책이 가능합니다.',
    stock: 28,
    status: '판매중',
    rating: 4.5,
    reviewCount: '134개 리뷰',
    isNew: true,
    discount: '22% 할인',
    views: 189,
    likes: 34,
    favorites: 41
  },
  {
    no: 52,
    name: '강아지 목줄',
    price: 15000,
    originalPrice: 20000,
    category: '산책',
    imageUrl: walkDogNeckLeash,
    description: '편안하고 안전한 강아지 목줄입니다. 조절 가능한 길이와 부드러운 재질로 산책이 즐거워집니다.',
    stock: 45,
    status: '판매중',
    rating: 4.4,
    reviewCount: '176개 리뷰',
    isNew: false,
    discount: '25% 할인',
    views: 156,
    likes: 28,
    favorites: 34
  },
  {
    no: 53,
    name: '강아지 신발',
    price: 18000,
    originalPrice: 24000,
    category: '액세서리',
    imageUrl: walkDogShoes,
    description: '강아지 발을 보호하는 전용 신발입니다. 방수 기능과 미끄럼 방지 밑창으로 안전한 산책을 도와줍니다.',
    stock: 32,
    status: '판매중',
    rating: 4.3,
    reviewCount: '87개 리뷰',
    isNew: true,
    discount: '25% 할인',
    views: 112,
    likes: 20,
    favorites: 25
  },
  {
    no: 54,
    name: '펫 산책가방',
    price: 22000,
    originalPrice: 28000,
    category: '산책',
    imageUrl: walkPetBag,
    description: '산책 시 필요한 용품을 담을 수 있는 펫 전용 가방입니다. 물병, 간식, 배변봉투 등을 수납할 수 있습니다.',
    stock: 26,
    status: '판매중',
    rating: 4.4,
    reviewCount: '98개 리뷰',
    isNew: false,
    discount: '21% 할인',
    views: 134,
    likes: 24,
    favorites: 29
  },
  {
    no: 55,
    name: '산책용 물병',
    price: 12000,
    originalPrice: 16000,
    category: '산책',
    imageUrl: walkWaterContainer,
    description: '산책 중 반려동물에게 물을 줄 수 있는 휴대용 물병입니다. 컵과 일체형 구조로 편리합니다.',
    stock: 58,
    status: '판매중',
    rating: 4.2,
    reviewCount: '145개 리뷰',
    isNew: true,
    discount: '25% 할인',
    views: 167,
    likes: 29,
    favorites: 35
  }
];

// API 응답 시뮬레이션 함수들
export const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

export const simulateApiCall = async (fn, data, delayMs = 100) => {
  await delay(delayMs);
  try {
    return {
      success: true,
      ...fn(data)
    };
  } catch (error) {
    return {
      success: false,
      error: error.message
    };
  }
};
