-- products 테이블이 존재하는지 확인하고 없으면 생성
CREATE TABLE IF NOT EXISTS products (
    no INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description TEXT,
    price INT NOT NULL DEFAULT 0,
    image_url VARCHAR(500),
    status VARCHAR(20) DEFAULT '판매중',
    stock INT DEFAULT 0,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    upd_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    views INT DEFAULT 0,
    likes INT DEFAULT 0
);

-- 샘플 데이터가 없으면 삽입
INSERT IGNORE INTO products (no, name, category, description, price, image_url, stock) VALUES
-- 55개 상품 데이터 (mockDatabase.js 기반)
(1, '강아지 사료', '사료', '영양 만점 강아지 사료로 반려견의 건강한 성장을 도와줍니다. 신선한 육류와 곡물로 만들어진 프리미엄 사료로, 강아지의 나이와 체중에 맞게 급여하시면 됩니다.', 25000, '/assets/dist/img/products/fooddogheartbeam.png', 50),
(2, '고양이 장난감 막대', '장난감', '고양이가 좋아하는 재미있는 장난감 막대입니다. 깃털과 방울이 달려있어 고양이의 사냥 본능을 자극하고 스트레스를 해소해줍니다.', 12000, '/assets/dist/img/products/toycatrod.png', 30),
(3, '펫 캐리어', '용품', '반려동물을 안전하게 이동시킬 수 있는 캐리어입니다. 통풍이 잘 되고 견고한 구조로 되어있어 장거리 이동에도 안전합니다.', 35000, '/assets/dist/img/products/productpetcarriage.png', 25),
(4, '새 모이', '사료', '새들이 좋아하는 영양 모이입니다. 다양한 곡물과 씨앗이 포함되어 새의 건강한 성장을 돕습니다.', 8000, '/assets/dist/img/products/foodbirdfallinlove.png', 40),
(5, '강아지 공', '장난감', '강아지가 좋아하는 탄력 있는 공입니다. 안전한 재질로 만들어져 실내외에서 안전하게 놀 수 있습니다.', 15000, '/assets/dist/img/products/toydogball.png', 35),
(6, '고양이 물그릇', '용품', '고양이 전용 물그릇입니다. 위생적이고 미끄럼 방지 바닥으로 안정적입니다.', 22000, '/assets/dist/img/products/productcatwaterbowl.png', 20),
(7, '강아지 하네스', '산책', '편안한 강아지 하네스입니다. 부드러운 재질로 강아지가 편안하게 산책할 수 있습니다.', 18000, '/assets/dist/img/products/productdogharness.png', 28),
(8, '펫 샴푸', '용품', '반려동물 전용 샴푸입니다. 민감한 피부에도 자극이 적고 부드럽게 세정합니다.', 16000, '/assets/dist/img/products/productpetshampoo.png', 32),
(9, '새 로프 장난감', '장난감', '새들이 좋아하는 로프 타입 장난감입니다. 자연 섬유로 만들어져 안전하고 재미있게 놀 수 있습니다.', 9000, '/assets/dist/img/products/birdropetype.png', 45),
(10, '새 놀이 장난감', '장난감', '새의 지능 발달에 도움이 되는 놀이 장난감입니다. 다양한 색상과 소재로 구성되어 있습니다.', 11000, '/assets/dist/img/products/birdtoy.png', 38),
(11, '부엉이 새 사료', '사료', '부엉이와 맹금류를 위한 특별한 사료입니다. 고단백 영양소가 풍부합니다.', 13000, '/assets/dist/img/products/foodbirdowlsee.png', 22),
(12, '새 전용 프리미엄 사료', '사료', '새들의 건강한 성장을 위한 프리미엄 사료입니다. 비타민과 미네랄이 균형있게 포함되어 있습니다.', 15000, '/assets/dist/img/products/foodbirdscream.png', 33),
(13, '고양이 건식 사료 50', '사료', '성묘를 위한 건식 사료입니다. 50일 분량으로 경제적이고 영양가가 풍부합니다.', 32000, '/assets/dist/img/products/foodcatfifty.png', 18),
(14, '고양이 생선맛 사료', '사료', '고양이가 좋아하는 생선맛 사료입니다. 오메가3가 풍부하고 소화가 잘 됩니다.', 28000, '/assets/dist/img/products/foodcatfishtaste.png', 26),
(15, '고양이 프리미엄 사료', '사료', '고급 재료로 만든 고양이 프리미엄 사료입니다. 털 윤기와 소화 건강을 동시에 케어합니다.', 35000, '/assets/dist/img/products/foodcatgoddu.png', 15),
(16, '강아지 사랑 사료', '사료', '강아지가 사랑하는 맛있는 사료입니다. 자연 재료로만 만들어져 건강하고 맛있습니다.', 29000, '/assets/dist/img/products/foodddogaddylovesit.png', 42),
(17, '강아지 고양이 건식 사료', '사료', '강아지와 고양이 모두 먹을 수 있는 건식 사료입니다. 다양한 영양소가 균형있게 포함되어 있습니다.', 26000, '/assets/dist/img/products/fooddogandcatdried.png', 37),
(18, '강아지 고양이 습식 사료', '사료', '수분이 풍부한 습식 사료입니다. 강아지와 고양이 모두에게 좋은 영양 공급원입니다.', 24000, '/assets/dist/img/products/fooddogcatmoistured.png', 29),
(19, '강아지 껌 사료', '사료', '강아지의 치아 건강에 도움이 되는 껌 타입 사료입니다. 씹는 재미와 영양을 동시에 제공합니다.', 18000, '/assets/dist/img/products/fooddoggum1.png', 55),
(20, '강아지 육류 사료', '사료', '신선한 육류를 주원료로 한 강아지 사료입니다. 고단백 저지방으로 건강한 성장을 돕습니다.', 38000, '/assets/dist/img/products/fooddogmeat.png', 21),
(21, '도마뱀 사료 접시', '용품', '도마뱀과 파충류를 위한 전용 사료 접시입니다. 청결하고 사용하기 편리합니다.', 12000, '/assets/dist/img/products/lizardfeedplate.png', 34),
(22, '도마뱀 케어 패키지', '용품', '도마뱀 사육에 필요한 모든 용품이 들어있는 패키지입니다. 초보자도 쉽게 시작할 수 있습니다.', 45000, '/assets/dist/img/products/lizardpackage.png', 12),
(23, '도마뱀 테라리움', '용품', '도마뱀을 위한 전문적인 테라리움입니다. 온도와 습도 조절이 가능하여 최적의 환경을 제공합니다.', 89000, '/assets/dist/img/products/lizardteralium.png', 8),
(24, '펫 스프레이 용기', '용품', '반려동물 케어용 스프레이 용기입니다. 미스트 타입으로 균일하게 분사됩니다.', 8000, '/assets/dist/img/products/petcontainerspray.png', 48),
(25, '펫 디지털 계량기', '용품', '정확한 사료 계량을 위한 디지털 계량기입니다. 반려동물의 적정 사료량 관리에 도움됩니다.', 25000, '/assets/dist/img/products/petdigitalmeasurer.png', 19),
(26, '펫 바닥 매트', '용품', '반려동물을 위한 바닥 보호 매트입니다. 미끄럼 방지와 충격 완화 기능이 있습니다.', 15000, '/assets/dist/img/products/petfloorpad.png', 41),
(27, '자동 급식기', '용품', '스마트 자동 급식기입니다. 정해진 시간에 자동으로 사료를 공급하여 규칙적인 식사를 도와줍니다.', 78000, '/assets/dist/img/products/petfoodautofeeder.png', 14),
(28, '펫 보온등', '용품', '파충류와 소동물을 위한 보온등입니다. 적절한 온도 유지로 건강한 환경을 제공합니다.', 35000, '/assets/dist/img/products/petheatlamp.png', 23),
(29, '펫 핀셋 급식기', '용품', '소형 펫을 위한 핀셋 타입 급식기입니다. 정확하고 위생적인 급식이 가능합니다.', 6000, '/assets/dist/img/products/petpinsetfeed.png', 52),
(30, '펫 쉘터', '용품', '반려동물을 위한 아늑한 쉘터입니다. 안전하고 편안한 휴식 공간을 제공합니다.', 42000, '/assets/dist/img/products/petshelter.png', 17),
(31, '자동 급수기', '용품', '물이 자동으로 보충되는 급수기입니다. 항상 신선한 물을 공급하여 반려동물의 건강을 지킵니다.', 32000, '/assets/dist/img/products/petwatercontainertypefeeder.png', 28),
(32, '고양이 방울 목걸이', '액세서리', '고양이를 위한 귀여운 방울 목걸이입니다. 안전한 재질로 만들어져 목에 부담을 주지 않습니다.', 9000, '/assets/dist/img/products/productcatbellnecklace.png', 46),
(33, '고양이 사료그릇', '용품', '고양이 전용 사료그릇입니다. 적절한 높이와 크기로 편안한 식사를 도와줍니다.', 18000, '/assets/dist/img/products/productcatbowl.png', 35),
(34, '고양이 위생패드', '위생용품', '고양이 화장실용 위생패드입니다. 흡수력이 뛰어나고 냄새 제거 기능이 있습니다.', 16000, '/assets/dist/img/products/productcathygienepad.png', 39),
(35, '강아지 사료그릇', '용품', '강아지를 위한 스테인리스 사료그릇입니다. 위생적이고 내구성이 뛰어납니다.', 20000, '/assets/dist/img/products/productdogbowl.png', 31),
(36, '강아지 위생패드', '위생용품', '강아지용 대형 위생패드입니다. 넓은 면적으로 흡수력이 우수하고 바닥 보호 효과가 있습니다.', 22000, '/assets/dist/img/products/productdoghygienepad.png', 44),
(37, '강아지 급수그릇', '용품', '강아지 전용 급수그릇입니다. 미끄럼 방지 바닥과 적절한 깊이로 설계되었습니다.', 17000, '/assets/dist/img/products/productdogwaterbowl.png', 38),
(38, '위생봉투', '위생용품', '반려동물 배변 처리용 위생봉투입니다. 생분해성 소재로 환경 친화적입니다.', 5000, '/assets/dist/img/products/producthygieneplasticbag.png', 89),
(39, '펫 화장실', '위생용품', '실내용 펫 화장실입니다. 냄새 차단과 청소가 쉬운 구조로 설계되었습니다.', 35000, '/assets/dist/img/products/producthygienetoilet.png', 16),
(40, '펫 침대', '용품', '반려동물을 위한 편안한 침대입니다. 부드러운 소재와 적절한 쿠션감으로 숙면을 도와줍니다.', 28000, '/assets/dist/img/products/productpetbed.png', 25),
(41, '펫 케이지', '용품', '안전하고 튼튼한 펫 케이지입니다. 접이식 구조로 보관과 이동이 편리합니다.', 65000, '/assets/dist/img/products/productpetcage.png', 11),
(42, '펫 빗', '미용용품', '반려동물 전용 빗입니다. 부드러운 핀으로 털 엉킴을 방지하고 마사지 효과도 있습니다.', 12000, '/assets/dist/img/products/productpetcomb.png', 47),
(43, '펫 쿠션', '용품', '반려동물을 위한 편안한 쿠션입니다. 방수 커버로 세탁이 쉽고 위생적입니다.', 24000, '/assets/dist/img/products/productpetcousion.png', 33),
(44, '펫 발톱깎이', '미용용품', '안전한 펫 발톱깎이입니다. 날카로운 날과 안전장치로 정확하고 안전한 발톱 관리가 가능합니다.', 8000, '/assets/dist/img/products/productpetcutter.png', 56),
(45, '펫 귀 청소제', '미용용품', '반려동물 귀 전용 청소제입니다. 순한 성분으로 안전하게 귀 건강을 관리할 수 있습니다.', 15000, '/assets/dist/img/products/productpetearcleaner.png', 41),
(46, '펫 하우스', '용품', '반려동물을 위한 아늑한 하우스입니다. 실내외 모두 사용 가능하며 조립이 간단합니다.', 45000, '/assets/dist/img/products/productpethouse.png', 19),
(47, '펫 목걸이', '액세서리', '반려동물용 패션 목걸이입니다. 다양한 디자인으로 개성을 표현할 수 있습니다.', 13000, '/assets/dist/img/products/productpetnecklace.png', 37),
(48, '고양이 스마트 레이저 장난감', '장난감', '자동으로 움직이는 스마트 레이저 장난감입니다. 고양이의 운동량 증가와 스트레스 해소에 도움됩니다.', 35000, '/assets/dist/img/products/toycatsmartlaser.png', 22),
(49, '강아지 뼈다귀 장난감', '장난감', '강아지가 좋아하는 뼈다귀 모양 장난감입니다. 안전한 소재로 만들어져 오래 씹어도 안전합니다.', 10000, '/assets/dist/img/products/toydogbone.png', 48),
(50, '강아지 로프 장난감', '장난감', '천연 소재로 만든 강아지 로프 장난감입니다. 치아 건강에 도움이 되고 놀이와 훈련에 활용할 수 있습니다.', 7000, '/assets/dist/img/products/toydogrope.png', 62),
(51, 'LED 강아지 목줄', '산책', '야간 산책을 위한 LED 강아지 목줄입니다. 충전식 배터리와 다양한 점멸 모드로 안전한 야간 산책이 가능합니다.', 25000, '/assets/dist/img/products/walkdogLEDleash.png', 28),
(52, '강아지 목줄', '산책', '편안하고 안전한 강아지 목줄입니다. 조절 가능한 길이와 부드러운 재질로 산책이 즐거워집니다.', 15000, '/assets/dist/img/products/walkdogneckleash.png', 45),
(53, '강아지 신발', '액세서리', '강아지 발을 보호하는 전용 신발입니다. 방수 기능과 미끄럼 방지 밑창으로 안전한 산책을 도와줍니다.', 18000, '/assets/dist/img/products/walkdogshoes.png', 32),
(54, '펫 산책가방', '산책', '산책 시 필요한 용품을 담을 수 있는 펫 전용 가방입니다. 물병, 간식, 배변봉투 등을 수납할 수 있습니다.', 22000, '/assets/dist/img/products/walkpetbag.png', 26),
(55, '산책용 물병', '산책', '산책 중 반려동물에게 물을 줄 수 있는 휴대용 물병입니다. 컵과 일체형 구조로 편리합니다.', 12000, '/assets/dist/img/products/walkwatercontainer.png', 58);
